services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: equipe_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-equipe:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/equipe_db?&createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5Dialect"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
